version: '2'

networks:
  mynetwork.com:
    name: net_byfn
    external: true

services:
    caliper:
        container_name: caliper
        image: hyperledger/caliper:0.5.0
        command: launch manager
        environment:
        - CALIPER_BIND_SUT=fabric:2.2
        - CALIPER_BENCHCONFIG=benchmarks/samples/fabric/hedera/config.yaml
        - CALIPER_NETWORKCONFIG=networks/fabric/test-network.yaml
        - CALIPER_FLOW_ONLY_TEST
        - CALIPER_FABRIC_GATEWAY_LOCALHOST=false
        - CALIPER_FABRIC_GATEWAY_ENABLED
        - GRPC_TRACE=all
        - GRPC_VERBOSITY=DEBUG
        volumes:
        - ./caliper-benchmarks:/hyperledger/caliper/workspace
        - ../first-network:/hyperledger/caliper/first-network
        networks:
        - mynetwork.com
