test:
  workers:
    number: 5
  rounds:
    - label: invoke
      txDuration: 60
      rateControl:
        type: fixed-load
        opts:
          transactionLoad: 5
      workload:
        module: benchmarks/samples/fabric/hedera/invoke.js
